# Generated by Django 4.1.3 on 2023-05-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=300)),
                ('middlename', models.CharField(max_length=300)),
                ('lastname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
