# Generated by Django 4.2.1 on 2023-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountusers",
            old_name="firstname",
            new_name="username",
        ),
        migrations.RemoveField(
            model_name="accountusers",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="accountusers",
            name="middlename",
        ),
        migrations.AlterField(
            model_name="accountusers",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
